services:
  web:
    build: .
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
      - "4343:443"
      - "4343:443/udp"
    volumes:
      - $PWD/conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    env_file: .env

volumes:
  caddy_data:
  caddy_config:
